version: "3.9"

services:

  web:
    build: ./web
    ports:
      - 18888:8888
      - 19100:9100
    command: ./start.sh
    labels:
      - group=application
  
  prometheus:
    image: bitnami/prometheus:2.50.1
    ports:
      - 19090:9090
    depends_on:
      - web
    labels:
      - group=monitoring

  grafana:
    build: ./grafana
    ports:
      - 13000:3000
    depends_on:
      - prometheus
    labels:
      - group=monitoring


networks:
  default:
    name: everseen
