version: "3.9"

services:

  web:
    build: web
    ports:
      - 18888:8888
      - 19100:9100
    entrypoint: sh -x entrypoint.sh
    labels:
      - group=application

  prometheus:
    image: bitnami/prometheus:2.50.1
    ports:
      - 19090:9090
    labels:
      - group=monitoring
    volumes:
      - type: volume
        source: prometheus_config
        target: /opt/bitnami/prometheus/conf

  grafana:
#    build: grafana
    image: grafana/grafana:10.0.12
    ports:
      - 13000:3000
    labels:
      - group=monitoring
    volumes:
      - type: volume
        source: grafana_db
        target: /var/lib/grafana

volumes:
  prometheus_config:
    external: false
  grafana_db:
    external: false

networks:
  default:
    name: everseen
